### ISSUE TITLE
Styling question

### ISSUE THREAD

**Issue by RCatersels** [AuraQ/ClockPickerForMendix#1]
Thank you for such a quick sollution :)
I noticed in the CSS that the styling is set as:
float: left;
padding-left: 15px;
padding-right: 15px;

Any reason for that? Because now the widget never lines with other objects in a grid. I used float right and zero padding myself. 

Regards,

Ronald

**Comment by lindski** [comment]
No worries :)

The styles for the widget have come from the underlying plugin but I can't see anywhere in the css where the styles you mention have been specified.

Whereabouts are you seeing these styles set?

Could it be that these are being inherited from Mendix/Bootstrap?

Cheers

Iain

**Comment by RCatersels** [comment]
Thanks, my mistake. It's the bootstrap that is indeed causing this.
