### ISSUE TITLE
ClockPicker seems to change date aswell

### ISSUE THREAD

**Issue by stephanbruijnis** [AuraQ/ClockPickerForMendix#5]
Hi,

When I add the widget to a page with a dateTime attribuut (default value CurrentDateTime) with localize yes. For today that would be 2016-08-12 15:54. If I set the time to 00:05 the date jumps to 2016-08-13 00:05. Instead of 2016-08-12 00:05

I will add a test project soon, but I wanted to inform you about this behaviour.

With kind regards,
Stephan

**Comment by stephanbruijnis** [comment]
Closed issue (not an issue).  Made a reproduction project and the behaviour is what you would expect.
1. Create object. With a dateTime attribute set to 17-08-2016 10:31 (session time, CET + 2:00) so 17-08-2016 08:31 UTC
2. Change the time on the object via the ClockPicker to 00:05
3. dateTime attribute on object will be set to 17-08-2016 00:05 (session time, CET + 2:00) so 16-08-2016 22:05 UTC

Which is ok :+1:

**Comment by lindski** [comment]
Great, thanks for updating!
