### ISSUE TITLE
When  using 12-hour format and select PM, 12 it shift one day forward

### ISSUE THREAD

**Issue by pimvdnoll** [AuraQ/ClockPickerForMendix#6]
24-hour option is working fine (and for now a workaround) but appreciate if you can get this working for the 12-hour format as well.

**Comment by lindski** [comment]
Widget wasn't correctly handling the hours correctly when using a 12 hour clock and selecting a time of 12:mm PM.

This should now be fixed in commit de30a84

Widget available in the test folder and will also do a new release for the app store.

**Comment by pimvdnoll** [comment]
Thanks!

**Comment by pimvdnoll** [comment]
please update the appstore release as well :)

**Comment by lindski** [comment]
Have submitted for approval today.

**Comment by lindski** [comment]
Version 1.0.2 now available on the appstore
