### ISSUE TITLE
Position Issue With Mendix

### ISSUE THREAD

**Issue by sirazmillath** [AuraQ/ClockPickerForMendix#7]
1. I added the Clock Picker in the Mendix.
2. When I click the clock, its change the right scrollbar and then picker move with the scroll.

Add image for your reference. I'm using Mendix 6.10.2
![001-clockissue](https://cloud.githubusercontent.com/assets/25412357/22402351/a2585196-e60d-11e6-9290-6e9b6e2cc257.jpg)
![002-clockissue](https://cloud.githubusercontent.com/assets/25412357/22402352/a25d4a02-e60d-11e6-8392-824a1b218ad3.jpg)
![003-clockissue](https://cloud.githubusercontent.com/assets/25412357/22402353/a2a21f9c-e60d-11e6-9273-66defb4cdd6d.jpg)

**Comment by lindski** [comment]
This should be addressed by commit ae648ca which now ensures the picker is tied to the input element.

I will create a new release and publish this to the app store (in the meantime you can grab the latest widget from the test project)

**Comment by sirazmillath** [comment]
Hello Lain Lindsay,

Thank you very much for fixed the issue and it's working fine. [😊]
